import mongoose from "mongoose";

const movieSchema = new mongoose.Schema({
    movie_id:{
        type:Number,
        required:true
    },
    title:{
        type:String,
        required:true
    },
    language:{
        type:String,
        required:true
    },
    overview:{
        type:String,
        default:"UNAVAILABLE"
    },
    release_date:{
        type:Date,
        required:true
    },
    popularity:{
        type:Number,
        default:0
    },
    rating:{
        type:Number,
        default:0
    },
    genres:{
        type:Array,
        default:[]
    },
    video_link:{
        type:String,
        default:null
    },
    runtime:{
        type:Number,
        default:0
    },
    movie_status:{
        type:String,
        required:true
    },
    backdrop_path:{
        type:String,
        required:true
    },
    poster_path:{
        type:String,
        required:true
    },
    cast:[{
        cast_id:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'people'
        },
        character:{
            type:String,
            default:''
        }
    }],
    crew:[{
        crew_id:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'people'
        }
    }]
})

export default mongoose.model('movie',movieSchema)